on:
  rss:
    url:
      - https://rss-five-blue.vercel.app/zhihu/posts/people/knowyourself-1
      - https://rss-five-blue.vercel.app/zhihu/people/answers/knowyourself-1
      - https://rss-five-blue.vercel.app/medsci/40
      - http://8.137.58.98:4000/feeds/MP_WXS_3213027136.atom
      - http://8.137.58.98:4000/feeds/MP_WXS_3257586869.atom
      - http://8.137.58.98:4000/feeds/MP_WXS_3202238386.atom
      - http://8.137.58.98:4000/feeds/MP_WXS_3274473737.atom
      - http://8.137.58.98:4000/feeds/MP_WXS_3091816442.atom
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.APIPROTECT }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}",
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSS news"
            }
