on:
  rss:
    url:
      - RSS: https://rss-five-blue.vercel.app/zhihu/posts/people/knowyourself-1
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://cubox.pro/c/api/save/j1e6dt99t3kaln
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}",
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSSCuboxfolder"
            }
