on:
  rss:
    url:
      - https://rss-five-blue.vercel.app/zhihu/posts/people/knowyourself-1
      - https://rss-five-blue.vercel.app/zhihu/people/answers/knowyourself-1
      - https://jamaisvu.website/bilibili/user/dynamic/37648256
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.APIPROTECT }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}",
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSS news"
            }
